src/api/urls.py
from django.urls import path
from .import views

app_name = 'api'

urlpatterns = [
    path('coordinadores/', views.CoordinadorListAPIView.as_view(), name='listar_coordinadores'),
    path('coordinadores/<int:pk>/', views.CoordinadorRetrieveAPIView.as_view(), name='buscar_coordinador'),
    path('empleados/', views.EmpleadoListAPIView.as_view(), name='listar_empleados'),
    path('empleados/<int:pk>', views.EmpleadoRetrieveAPIView.as_view(), name='buscar_empleado'),
    path('reservas/', views.ReservaListAPIView.as_view(), name='listar_reservas'),
    path('reservas/<int:pk>', views.ReservaRetrieveAPIView.as_view(), name='buscar_reserva'),
    path('clientes/', views.ClienteListAPIView.as_view(), name='listar_cliente'),
    path('clientes/<int:pk>/', views.ClienteRetrieveAPIView.as_view(), name='buscar_cliente'),
    path('servicios/', views.ServicioListAPIView.as_view(), name='listar_servicio'),
    path('servicios/<int:pk>/', views.ServicioRetrieveAPIView.as_view(), name='buscar_servicio'),
    path('documentacion/', views.api_documentacion, name='documentacion' )
]

src/app_reservas/urls.py
from django.urls import path
from .import views

app_name = 'app_reservas'

urlpatterns = [
    path('listado/', views.ReservasListView.as_view(), name='listado_reservas' ),
    path('nuevo/', views.ReservasCreateView.as_view(), name='registrar_reserva'),
    path('modificar/<int:pk>', views.ReservasUpdateView.as_view(), name='actualizar_reserva' ),
    path('eliminar/<int:pk>/', views.ReservaServicioDeleteView.as_view(), name='eliminar_reserva')
]

src/webapp_reservas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('app_clientes.urls', namespace='clientes')),
    path('coordinadores/', include('app_coordinadores.urls', namespace='coordinadores')),
    path('empleados/', include('app_empleados.urls', namespace='empelados')),
    path('servicios/', include('app_servicios.urls', namespace='servicios')),
    path('reservas/', include('app_reservas.urls', namespace='reservas')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('homepage.urls', namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/reservas/actualizar_reserva.html
{% extends "base.html" %}

{% block titulo %}

ACTUALIZAR RESERVA

{% endblock titulo %}

{% block contenido %}

<div>
    <h2 align="center"> ACTUALIZAR RESERVA DE SERVICIO</h2>

    <style>
        .my-form {
            max-width: 500px;
            margin: auto;
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
        }

        .my-form.input {
            border: 2px solid #428bca;
            border-radius: 5px;
            margin-bottom: 10px;
        }
    </style>

    <form action="" method="POST" enctype='multipart/form' class="my-form" align="center">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>

        <button type="submit" class="btn btn-success" style="margin-top: 20px;">Actualizar Reserva</button>
    </form>
    <div align="center" style="margin-top: 40px">
        <a href="{% url 'app_reservas:listado_reservas' %}">
            <button type="button" class="btn btn-secondary">Volver al listado</button>
        </a>
    </div>
</div>
{% endblock %}

src/templates/reservas/eliminar_reserva.html
{% extends "base.html" %}

{% block titulo %}

Eliminación de reserva

{% endblock titulo %}

{% block contenido %}

<div>
    <h2 class="mt-4" align="center">ELIMINAR RESERVA</h2>

    <form method="post" action="{% url 'app_reservas:eliminar_reserva' object.pk %}" align="center">
        {% csrf_token %}

        <p>¿Estás seguro de que quieres eliminar la reserva?</p>

        {{ form }}

        <input type="submit" class="btn btn-danger" value="Eliminar">
    </form>

    <div align="center" style="margin-top: 40px">
        <a href="{% url 'app_reservas:listado_reservas' %}">
            <button type="button" class="btn btn-secondary">Volver al listado</button>
        </a>
    </div>
</div>
{% endblock contenido %}

src/templates/reservas/formulario_reserva.html
{% extends "base.html" %}

{% block contenido %}

<h2>RESERVA DE SERVICIO</h2>
<form method="POST" enctype="multipart/form-data">
    <table>
        {{ form.as_table }}
        {% csrf_token %}
    </table>
    <button type="submit">{{mensaje_boton}} </button>
</form>
<!-- <div class="alert alert-primary" role="alert">
    <a href="{% url 'app_reservas:listado_reservas' %}" class="alert-link"> Click acá </a> para volver al listado.
</div>-->
{% endblock contenido%}

src/templates/reservas/lista_reservas.html
{% extends 'base.html'%}

{% block titulo %} LISTA RESERVAS {% endblock titulo%}

{% block contenido %}

<div class="container mt-4">

  <h2 align="center" class="mb-4">LISTADO DE RESERVAS DE SERVICIOS </h2>

  <a href="{% url 'app_reservas:registrar_reserva' %}">
    <button type="button" class="btn btn-primary" style="margin-bottom: 30px;">Nueva reserva</button>
  </a>

  <table class="table table-hover">
    <thead align="center">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Fecha reservada</th>
        <th scope="col">Cliente</th>
        <th scope='col'>Servicio</th>
        <th scope='col'>Coordinador</th>
        <th scope='col'>Empleado que reservó</th>
        <th scope="col">Fecha de reserva</th>
        <th scope='col'> </th>
        <th scope='col'> </th>
      </tr>
    </thead>
    <tbody align="center">

      {% for reserva in reservas%}
      <tr>
        <th scope="row"> {{reserva.pk}}</th>
        <td>{{ reserva.fecha_reservada }}</td>
        <td>{{ reserva.cliente.apellido }} {{ reserva.cliente.nombre }}</td>
        <td>{{ reserva.servicio}}</td>
        <td>{{ reserva.coordinador.apellido }} {{ reserva.coordinador.nombre }}</td>
        <td>{{ reserva.empleado.apellido }} {{ reserva.empleado.nombre }}</td>
        <td>{{ reserva.fecha_reserva }}</td>
        <td> <a href="{% url 'app_reservas:actualizar_reserva' reserva.pk %}"> <button type="button"
              class="btn btn-outline-warning">Modificar</button> </a> </td>
        <td> <a href="{% url 'app_reservas:eliminar_reserva' reserva.pk %}"> <button type="button"
              class="btn btn-outline-danger">Eliminar</button> </td>
      </tr>
      {% endfor%}

    </tbody>
  </table>

  {%endblock contenido%}

src/templates/reservas/nueva_reserva.html
{% extends "base.html" %}

{% block titulo %} REGISTRAR RESERVA{% endblock titulo %}

{% block contenido %}

<div>
    <h2 class="mt-4" align="center"> RESERVA DE SERVICIO </h2>

    <style>
        .my-form {
            max-width: 500px;
            margin: auto;
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
        }

        .my-form.input {
            border: 2px solid #428bca;
            border-radius: 5px;
            margin-bottom: 10px;
        }
    </style>

    <form action="" method="POST" enctype='multipart/form' class="my-form" align="center">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>

        <button type="submit" class="btn btn-success" style="margin-top: 20px;">Nueva Reserva</button>
    </form>

    <div align="center" style="margin-top: 40px">
        <a href="{% url 'app_reservas:listado_reservas' %}">
            <button type="button" class="btn btn-secondary">Volver al listado</button>
        </a>
    </div>
</div>
{% endblock %}