src/api/urls.py
from django.urls import path
from .import views

app_name = 'api'

urlpatterns = [
    path('coordinadores/', views.CoordinadorListAPIView.as_view(), name='listar_coordinadores'),
    path('coordinadores/<int:pk>/', views.CoordinadorRetrieveAPIView.as_view(), name='buscar_coordinador'),
    path('empleados/', views.EmpleadoListAPIView.as_view(), name='listar_empleados'),
    path('empleados/<int:pk>', views.EmpleadoRetrieveAPIView.as_view(), name='buscar_empleado'),
    path('reservas/', views.ReservaListAPIView.as_view(), name='listar_reservas'),
    path('reservas/<int:pk>', views.ReservaRetrieveAPIView.as_view(), name='buscar_reserva'),
    path('clientes/', views.ClienteListAPIView.as_view(), name='listar_cliente'),
    path('clientes/<int:pk>/', views.ClienteRetrieveAPIView.as_view(), name='buscar_cliente'),
    path('servicios/', views.ServicioListAPIView.as_view(), name='listar_servicio'),
    path('servicios/<int:pk>/', views.ServicioRetrieveAPIView.as_view(), name='buscar_servicio'),
    path('documentacion/', views.api_documentacion, name='documentacion' )
]

src/app_coordinadores/urls.py
from django.urls import path
from .import views

app_name = 'app_coordinadores'

urlpatterns = [
   
    path('listado/', views.listado_coordinadores, name='listado_coordinadores'),
    path('modificar/<int:id>/', views.actualizar_coordinador, name='actualizar_coordinador'),
    path('nuevo/', views.CoordinadorCreateView.as_view(), name='crear_coordinador'),
    path('activar/<int:id>/', views.activar_coordinador, name='activar_coordinador'),
    path('desactivar/<int:id>', views.desactivar_coordinador, name='desactivar_coordinador'),
]

src/webapp_reservas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('app_clientes.urls', namespace='clientes')),
    path('coordinadores/', include('app_coordinadores.urls', namespace='coordinadores')),
    path('empleados/', include('app_empleados.urls', namespace='empelados')),
    path('servicios/', include('app_servicios.urls', namespace='servicios')),
    path('reservas/', include('app_reservas.urls', namespace='reservas')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('homepage.urls', namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/coordinadores/actualizar_coordinador.html
{% extends "base.html" %}

{% block titulo %}

ACTUALIZACION COORDINADOR

{% endblock titulo %}

{% block contenido %}

<div>
    <h2 class="mt-4" align="center"> ACTUALIZAR COORDINADOR</h2>

    <style>
        .my-form {
            max-width: 500px;
            margin: auto;
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
        }

        .my-form.input {
            border: 2px solid #428bca;
            border-radius: 5px;
            margin-bottom: 10px;
        }
    </style>

    <form action="" , method="POST" , enctype='multipart/form' class="my-form" align="center">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p}}
        </div>
        <button type="submit" class="btn btn-success" style="margin-top: 20px;">Actualizar Coordinador</button>
    </form>
    <div align="center" style="margin-top: 40px">
        <a href="{% url 'app_coordinadores:listado_coordinadores' %}">
            <button type="button" class="btn btn-secondary">Volver al listado</button>
        </a>
    </div>
</div>
{% endblock %}

src/templates/coordinadores/formulario_coordinadores.html
{% extends "base.html" %}

{% block contenido%}

<h2> REGISTRAR O ACTUALIZAR COORDINADOR</h2>

<form action="" , method="POST" , enctype='multipart/form'>
    <table>
        {{ form.as_table }}
        {% csrf_token %}
    </table>
    <button type="submit">{{mensaje_boton}} </button>
</form>
<div class="alert alert-primary" role="alert">
    <a href="{% url 'coordinadores:listado_coordinadores' %}" class="alert-link"> Click acá </a> para volver al listado.
</div>
{% endblock contenido%}

src/templates/coordinadores/lista_coordinadores.html
{% extends 'base.html' %}

{% block titulo %} LISTA COORDINADORES {% endblock titulo%}

{% block contenido%}

<div class="container mt-4">

  <h2 align="center" class="mb-4">LISTADO DE COORDINADORES</h2>

  <a href="{% url 'app_coordinadores:crear_coordinador' %}">
    <button type="button" class="btn btn-primary" style="margin-bottom: 30px;">Nuevo coordinador</button>
  </a>

  <table class="table table-hover">
    <thead align="center">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Activo</th>
        <th scope='col'> </th>
        <th scope='col'> </th>
        <th scope='col'> </th>
      </tr>
    </thead>
    <tbody align="center">

      {% for coordinador in coordinadores %}
      <tr>
        <th scope="row">{{coordinador.id}}</th>
        <td>{{ coordinador.nombre }}</td>
        <td>{{ coordinador.apellido }}</td>
        <td>
          {% if coordinador.activo %}
          <i class="fas fa-check-circle text-success"></i>
          {% else %}
          <i class="fas fa-times-circle text-danger"></i>
          {% endif %}
        </td>
        <td>
          <a href="{% url 'app_coordinadores:actualizar_coordinador' coordinador.pk %}">
            <button type="button" class="btn btn-outline-warning">Modificar</button>
          </a>
        </td>
        <td>
          {% if coordinador.activo %}
          <a href="{% url 'app_coordinadores:desactivar_coordinador' coordinador.pk %}">
            <button type="button" class="btn btn-outline-danger"> Desactivar</button>
          </a>
          {% else %}
          <button type="button" class="btn btn-light" disabled>Desactivar</button>
          {% endif %}
        </td>
        <td>
          {% if not coordinador.activo %}
          <a href="{% url 'app_coordinadores:activar_coordinador' coordinador.pk %}">
            <button type="button" class="btn btn-outline-success">Activar</button>
          </a>
          {% else %}
          <button type="button" class="btn btn-light" disabled>Activar</button>
          {% endif %}
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>

{% endblock contenido %}

src/templates/coordinadores/nuevo_coordinador.html
{% extends "base.html" %}

{% block titulo %} REGISTRAR COORDINADOR{% endblock titulo %}

{% block contenido %}

<div>
    <h2 class="mt-4" align="center"> REGISTRAR COORDINADOR</h2>

    <style>
        .my-form {
            max-width: 500px;
            margin: auto;
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
        }

        .my-form.input {
            border: 2px solid #428bca;
            border-radius: 5px;
            margin-bottom: 10px;
        }
    </style>

    <form action="" , method="POST" , enctype='multipart/form' class="my-form" align="center">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-success" style="margin-top: 20px;">Registrar Coordinador</button>
    </form>

    <div align="center" style="margin-top: 40px">
        <a href="{% url 'app_coordinadores:listado_coordinadores' %}">
            <button type="button" class="btn btn-secondary">Volver al listado</button>
        </a>
    </div>
</div>

{% endblock %}