src/api/urls.py
from django.urls import path
from .import views

app_name = 'api'

urlpatterns = [
    path('coordinadores/', views.CoordinadorListAPIView.as_view(), name='listar_coordinadores'),
    path('coordinadores/<int:pk>/', views.CoordinadorRetrieveAPIView.as_view(), name='buscar_coordinador'),
    path('empleados/', views.EmpleadoListAPIView.as_view(), name='listar_empleados'),
    path('empleados/<int:pk>', views.EmpleadoRetrieveAPIView.as_view(), name='buscar_empleado'),
    path('reservas/', views.ReservaListAPIView.as_view(), name='listar_reservas'),
    path('reservas/<int:pk>', views.ReservaRetrieveAPIView.as_view(), name='buscar_reserva'),
    path('clientes/', views.ClienteListAPIView.as_view(), name='listar_cliente'),
    path('clientes/<int:pk>/', views.ClienteRetrieveAPIView.as_view(), name='buscar_cliente'),
    path('servicios/', views.ServicioListAPIView.as_view(), name='listar_servicio'),
    path('servicios/<int:pk>/', views.ServicioRetrieveAPIView.as_view(), name='buscar_servicio'),
    path('documentacion/', views.api_documentacion, name='documentacion' )
]

src/app_servicios/urls.py
from django.urls import path
from .import views

app_name = 'app_servicios'

urlpatterns = [
    path('nuevo/', views.ServiciosCreateView.as_view(), name='registrar_servicio'),
    path('listado/', views.ServiciosListView.as_view(), name='listado_servicios'),
    path('modificar/<int:pk>/', views.ServiciosUpdateView.as_view(), name='actualizar_servicio'),
    path('activar/<int:id>/', views.activar_servicio, name="activar_servicio"),
    path('desactivar/<int:id>/', views.desactivar_servicio, name="desactivar_servicio"),
]

src/webapp_reservas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('app_clientes.urls', namespace='clientes')),
    path('coordinadores/', include('app_coordinadores.urls', namespace='coordinadores')),
    path('empleados/', include('app_empleados.urls', namespace='empelados')),
    path('servicios/', include('app_servicios.urls', namespace='servicios')),
    path('reservas/', include('app_reservas.urls', namespace='reservas')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('homepage.urls', namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/servicios/formulario_servicios.html
{% extends "base.html" %}

{% block titulo %} FORMULARIO SERVICIO{% endblock titulo %}

{% block contenido %}

<div>
    <h2 class="mt-4" align="center">FORMULARIO DE SERVICIO</h2>

    <style>
        .my-form {
            max-width: 500px;
            margin: auto;
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
        }

        .my-form.input {
            border: 2px solid #428bca;
            border-radius: 5px;
            margin-bottom: 10px;
        }
    </style>

    <form action="" method="POST" enctype='multipart/form' class="my-form">
        {% csrf_token %}
        <div class="mb-3">
            <table>
                {{ form.as_table }}
            </table>
        </div>

        <button type="submit" class="btn btn-success" style="margin-top: 20px;">{{mensaje_boton}}</button>
    </form>

    <div align="center" style="margin-top: 40px">
        <a href="{% url 'app_servicios:listado_servicios' %}">
            <button type="button" class="btn btn-secondary">Volver al listado</button>
        </a>
    </div>
</div>
{% endblock contenido%}

src/templates/servicios/lista_servicios.html
{% extends 'base.html'%}

{% block titulo %} LISTA CLIENTES {% endblock titulo%}

{% block contenido%}

<div class="container mt-4">

  <h2 align="center" class="mb-4">LISTADO DE SERVICIOS </h2>

  <a href="{% url 'app_servicios:registrar_servicio' %}">
    <button type="button" class="btn btn-primary" style="margin-bottom: 30px;">Nuevo servicio</button>
  </a>

  <table class="table table-hover">
    <thead align="center">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Descripción</th>
        <th scope="col">Precio</th>
        <th scope="col">Activo</th>
        <th scope='col'> </th>
        <th scope='col'> </th>
        <th scope='col'> </th>
      </tr>
    </thead>
    <tbody align="center">

      {% for servicio in servicios %}
      <tr>
        <th scope="row"> {{servicio.pk}}</th>
        <td>{{ servicio.nombre}}</td>
        <td>{{ servicio.descripcion}}</td>
        <td>{{ servicio.precio}}</td>
        <td>
          {% if servicio.activo %}
          <i class="fas fa-check-circle text-success"></i>
          {% else %}
          <i class="fas fa-times-circle text-danger"></i>
          {% endif %}
        </td>
        <td> <a href="{% url 'app_servicios:actualizar_servicio' servicio.pk %}"> <button type="button"
              class="btn btn-outline-warning">Modificar</button> </a> </td>
        <td>
          {% if servicio.activo %}
          <a href="{% url 'app_servicios:desactivar_servicio' servicio.pk %}"><button type="button"
              class="btn btn-outline-danger"> Desactivar</button> </a>
        </td>
        {% else %}
        <span> <button type="button" class="btn btn-light">Desactivar</button></span>
        {% endif %}
        <td>
          {% if not servicio.activo %}
          <a href="{% url 'app_servicios:activar_servicio' servicio.pk %}"><button type="button"
              class="btn btn-outline-success">Activar</button></a>
        </td>
        {% else %}
        <span> <button type="button" class="btn btn-light">Activar</button></span>
        {% endif %}
      </tr>
      {% endfor%}

    </tbody>
  </table>
</div>

{%endblock contenido%}

src/templates/servicios/listado_servicios.html
{% extends 'base.html'%}

{% block titulo %} LISTA DE SERVICIOS {% endblock titulo%}

{% block contenido%}

<div class="container mt-4"> <!-- Agrega un margen superior al contenedor principal -->


<h2 align="center" class="mb-4">LISTADO DE SERVICIOS</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Precio</th>
      <th scope="col">Activo</th>
      <th scope='col'>  </th>
      <th scope='col'>  </th>
      <th scope='col'> </th>
    </tr>
  </thead>
  <tbody>

    {% for servicio in servicios %} 
    <tr>
        <th scope="row"> {{servicio.id}}
      <!--
        <a href="{{ cliente.get_absolute_url}}"> 
        {{ cliente.pk}}
        </a>>
      --> 
        </th>
      <td>{{ servicio.nombre }}</td>
      <td>{{ servicio.descripcion }}</td>
      <td>{{ servicio.precio }}</td>
      <td>{{ servicio.activo }}</td>
      <td> <a href="{% url 'app_servicios:actualizar_servicio' servicio.pk %}"> <button type="button" class="btn btn-outline-warning">Modificar</button> </a> </td>
      <td> 
        {% if empleado.activo %}
            <a href="{% url 'app_servicios:estado_activo_servicio' servicio.pk %}"><button type="button" class="btn btn-outline-danger"> Desactivar</button> </a> </td>
        {% else %}
            <span> <button type="button" class="btn btn-light">Desactivar</button></span> 
        {% endif %}
      <td> 
        {% if not servicio.activo%}
            <a href="{% url 'app_servicios:estado_activo_servicio' servicio.pk %}"><button type="button" class="btn btn-outline-success">Activar</button></a> </td>
        {% else %}
            <span> <button type="button" class="btn btn-light">Activar</button></span>
        {% endif %}
    </tr> 
    {% endfor%}

  </tbody>
</table>

{%endblock contenido%}