src/api/urls.py
from django.urls import path
from .import views

app_name = 'api'

urlpatterns = [
    path('coordinadores/', views.CoordinadorListAPIView.as_view(), name='listar_coordinadores'),
    path('coordinadores/<int:pk>/', views.CoordinadorRetrieveAPIView.as_view(), name='buscar_coordinador'),
    path('empleados/', views.EmpleadoListAPIView.as_view(), name='listar_empleados'),
    path('empleados/<int:pk>', views.EmpleadoRetrieveAPIView.as_view(), name='buscar_empleado'),
    path('reservas/', views.ReservaListAPIView.as_view(), name='listar_reservas'),
    path('reservas/<int:pk>', views.ReservaRetrieveAPIView.as_view(), name='buscar_reserva'),
    path('clientes/', views.ClienteListAPIView.as_view(), name='listar_cliente'),
    path('clientes/<int:pk>/', views.ClienteRetrieveAPIView.as_view(), name='buscar_cliente'),
    path('servicios/', views.ServicioListAPIView.as_view(), name='listar_servicio'),
    path('servicios/<int:pk>/', views.ServicioRetrieveAPIView.as_view(), name='buscar_servicio'),
    path('documentacion/', views.api_documentacion, name='documentacion' )
]

src/app_clientes/urls.py
from django.urls import path
from . import views

app_name = 'app_clientes'

urlpatterns = [
    path('listado/', views.listado_clientes, name='listado_clientes'),
    path('nuevo/', views.ClientesCreateView.as_view(), name="registrar_cliente"),
    #path('modificar/<int:pk>/', views.ClientesUpdateView.as_view(), name="actualizar_cliente"),
    path('modificar/<int:id>/', views.actualizar_cliente, name='actualizar_cliente'),
    path('desactivar/<int:id>', views.desactivar_cliente, name='desactivar_cliente'),
    path('activar/<int:id>', views.activar_cliente, name="activar_cliente"),
]

src/webapp_reservas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('app_clientes.urls', namespace='clientes')),
    path('coordinadores/', include('app_coordinadores.urls', namespace='coordinadores')),
    path('empleados/', include('app_empleados.urls', namespace='empelados')),
    path('servicios/', include('app_servicios.urls', namespace='servicios')),
    path('reservas/', include('app_reservas.urls', namespace='reservas')),
    path('api/', include('api.urls', namespace='api')),
    path('', include('homepage.urls', namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/clientes/actualizar_cliente.html
{% extends "base.html" %}

{% block titulo %}

Actualización Cliente

{% endblock titulo %}

{% block contenido %}
<div>
    <style>
        .my-form {
            max-width: 500px;
            margin: auto;
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
        }

        .my-form.input {
            border: 2px solid #428bca;
            border-radius: 5px;
            margin-bottom: 10px;
        }
    </style>

    <h2 align="center">ACTUALIZAR CLIENTE</h2>

    <form action="" method="post" enctype="multipart/form-data" class="my-form" align="center">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success" style="margin-top: 20px;">Actualizar cliente</button>
    </form>

    <div align="center" style="margin-top: 40px">
        <a href="{% url 'app_clientes:listado_clientes' %}">
            <button type="button" class="btn btn-secondary">Volver al listado</button>
        </a>
    </div>
</div>
{% endblock %}

src/templates/clientes/formulario_clientes.html
{% extends "base.html" %}

{% block contenido%}

<h2> REGISTRAR O ACTUALIZAR CLIENTE</h2>

<form action="", method="POST", enctype='multipart/form'>
    <table>
        {{ form.as_table }}
        {% csrf_token %}
    </table>
    <button type="submit">{{mensaje_boton}} </button>
</form>
<div class="alert alert-primary" role="alert">
    <a href="{% url 'clientes:listado_clientes' %}" class="alert-link"> Click acá </a> para volver al listado. 
</div>
{% endblock contenido%}

src/templates/clientes/lista_clientes.html
{% extends 'base.html'%}

{% block titulo %} LISTA CLIENTES {% endblock titulo%}

{% block contenido %}

<div class="container mt-4">

  <h2 align="center" class="mb-4">LISTADO DE CLIENTES </h2>

  <a href="{% url 'app_clientes:registrar_cliente' %}">
    <button type="button" class="btn btn-primary" style="margin-bottom: 30px;">Nuevo cliente</button>
  </a>

  <table class="table table-hover">
    <thead align="center">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Activo</th>
        <th scope='col'> </th>
        <th scope='col'> </th>
        <th scope='col'> </th>
      </tr>
    </thead>
    <tbody align="center">

      {% for cliente in clientes %}
      <tr>
        <th scope="row"> {{cliente.id}}
        </th>
        <td>{{ cliente.nombre}}</td>
        <td>{{ cliente.apellido}}</td>
        <td>
          {% if cliente.activo %}
          <i class="fas fa-check-circle text-success"></i>
          {% else %}
          <i class="fas fa-times-circle text-danger"></i>
          {% endif %}
        </td>
        <td> <a href="{% url 'app_clientes:actualizar_cliente' cliente.pk %}"> <button type="button"
              class="btn btn-outline-warning">Modificar</button> </a> </td>
        <td>
          {% if cliente.activo %}
          <a href="{% url 'app_clientes:desactivar_cliente' cliente.pk %}"><button type="button"
              class="btn btn-outline-danger"> Desactivar</button> </a>
        </td>
        {% else %}
        <span> <button type="button" class="btn btn-light">Desactivar</button></span>
        {% endif %}
        <td>
          {% if not cliente.activo%}
          <a href="{% url 'app_clientes:activar_cliente' cliente.pk %}"><button type="button"
              class="btn btn-outline-success">Activar</button></a>
        </td>
        {% else %}
        <span> <button type="button" class="btn btn-light">Activar</button></span>
        {% endif %}
      </tr>
      {% endfor%}

    </tbody>
  </table>

  {%endblock contenido%}

src/templates/clientes/nuevo_cliente.html
{% extends "base.html" %}

{% block titulo %} REGISTRAR CLIENTE{% endblock titulo %}

{% block contenido %}

<div>
    <h2 class="mt-4" align="center">REGISTRAR CLIENTE</h2>

    <style>
        .my-form {
            max-width: 500px;
            margin: auto;
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
        }

        .my-form.input {
            border: 2px solid #428bca;
            border-radius: 5px;
            margin-bottom: 10px;
        }
    </style>

    <form action="" method="POST" enctype="multipart/form-data" class="my-form" align="center">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
        </div>
        <div class="mb-3">
            {{ form.apellido.label_tag }}
            {{ form.apellido }}
        </div>

        <button type="submit" class="btn btn-success" style="margin-top: 20px;">Registrar Cliente</button>
    </form>

    <div align="center" style="margin-top: 40px">
        <a href="{% url 'app_clientes:listado_clientes' %}">
            <button type="button" class="btn btn-secondary">Volver al listado</button>
        </a>
    </div>
</div>

{% endblock contenido %}